import '../../../core/audio/audio_manager.dart';
import '../models/runner_model.dart';
import '../models/level_model.dart';
import '../models/item_model.dart';
import '../models/power_up_model.dart';
import '../../../core/constants/game_constants.dart';
import 'runner_physics.dart';
import 'collision_engine.dart';
import 'obstacle_engine.dart';
import 'item_engine.dart';
import 'level_engine.dart';
import 'camera_engine.dart';
import 'score_engine.dart';

enum RunnerInputAction {
  laneLeft,
  laneRight,
  jump,
  slide,
}

enum RunEndReason {
  none,
  levelComplete,
  gameOver,
}

/// The single source of truth for one gameplay run.
///
/// Ties every sub-engine together and executes:
///
/// Input -> Physics -> Lane -> Obstacles -> Items
/// -> Collision -> Score -> Camera -> Render
///
/// Render is the caller's job; this class only computes gameplay state.
class RunnerEngine {
  final LevelModel level;

  final RunnerModel runner = RunnerModel();

  late final RunnerPhysics physics;
  late final LevelEngine levelEngine;

  final ObstacleEngine obstacleEngine = ObstacleEngine();
  final ItemEngine itemEngine = ItemEngine();
  final CollisionEngine collisionEngine = CollisionEngine();
  final ScoreEngine scoreEngine = ScoreEngine();
  final CameraEngine cameraEngine = CameraEngine();

  /// Current distance travelled by the runner.
  double distanceMeters = 0;

  /// Runner distance at the beginning of the current frame.
  ///
  /// CollisionEngine uses this together with [distanceMeters] to detect
  /// objects crossed between frames, preventing high-speed objects from
  /// being skipped.
  double previousDistanceMeters = 0;

  int _spawnedSegmentCount = 0;

  RunEndReason endReason = RunEndReason.none;

  double _hitInvulnerabilitySeconds = 0;

  RunnerEngine({
    required this.level,
    int? seed,
  }) {
    physics = RunnerPhysics(
      baseSpeed: level.baseSpeed,
      maxSpeedOverride: level.maxSpeed,
      accelerationOverride: level.acceleration,
    );

    levelEngine = LevelEngine(
      level: level,
      seed: seed,
    );

    runner.lives = GameConstants.startingLives;

    _spawnUpcomingSegments();
  }

  void handleInput(RunnerInputAction action) {
    switch (action) {
      case RunnerInputAction.laneLeft:
        physics.requestLaneChange(-1);
        break;
      case RunnerInputAction.laneRight:
        physics.requestLaneChange(1);
        break;
      case RunnerInputAction.jump:
        physics.jump();
        AudioManager.instance.playJump();
        break;
      case RunnerInputAction.slide:
        physics.slide();
        AudioManager.instance.playSlide();
        break;
    }
  }

  /// Advances the complete gameplay simulation by [dt] seconds.
  void update(double dt) {
    if (dt <= 0) return;
    if (endReason != RunEndReason.none) return;

    // Save the distance before advancing this frame.
    previousDistanceMeters = distanceMeters;

    // 1. Physics
    if (itemEngine.hasSpeedBoost) {
      physics.applySpeedMultiplier(
        1 + (GameConstants.speedBoostMultiplier - 1) * dt,
      );
    }
    physics.update(dt);

    // 2. Distance / world scroll
    distanceMeters += physics.forwardSpeed * dt;

    // 3. Obstacles + items (movement, spawning — spawning always ensures
    // the track is generated far enough ahead first; see
    // _spawnUpcomingSegments below, which is the fix for levels running
    // out of content while a non-distance goal is still unmet).
    obstacleEngine.update(dt, distanceMeters, physics.forwardSpeed);
    itemEngine.update(dt);
    _spawnUpcomingSegments();

    // 4. Collision
    _resolveCollisions();

    // 5. Score
    scoreEngine.update(dt);
    scoreEngine.updateDistance(distanceMeters);

    // 6. Level goal / checkpoints
    levelEngine.update(dt, distanceMeters);

    // 7. Camera
    cameraEngine.update(dt, physics.forwardSpeed);

    // 8. Runner visual state
    runner.state = physics.resolveState(
      isHit: _hitInvulnerabilitySeconds > 0 && runner.lives > 0,
    );
    if (_hitInvulnerabilitySeconds > 0) {
      _hitInvulnerabilitySeconds -= dt;
      if (_hitInvulnerabilitySeconds < 0) {
        _hitInvulnerabilitySeconds = 0;
      }
    }

    // 9. End conditions
    _checkEndConditions();
  }

  /// How far ahead of the player the track generator must have content
  /// ready. Speed-scaled and deliberately larger (in seconds) than the
  /// render visibility window in RunnerGameScreen, so spawned content is
  /// always already generated by the time it would enter view — this is
  /// the fix for obstacles "popping in" mid-road instead of appearing
  /// cleanly at the horizon.
  double get _spawnLookAheadDistance {
    final calculated = physics.forwardSpeed * GameConstants.spawnLookaheadSeconds;
    return calculated.clamp(
      GameConstants.minSpawnLookaheadMeters,
      GameConstants.maxSpawnLookaheadMeters,
    );
  }

  void _spawnUpcomingSegments() {
    final spawnLimit = distanceMeters + _spawnLookAheadDistance;

    // Extend the track (generating more segments if needed) up to the
    // spawn limit before reading it. This is what makes the track
    // effectively endless — a level with a "collect N cans" or "survive
    // N seconds" goal will never run out of obstacles/items while the
    // goal is still unmet, because more track is generated on demand
    // instead of being capped at level.distanceMeters once at the start.
    levelEngine.ensureGenerated(spawnLimit + GameConstants.minSpawnLookaheadMeters);

    final starts = levelEngine.segmentStartDistances;

    for (int i = _spawnedSegmentCount; i < levelEngine.segments.length; i++) {
      if (starts[i] > spawnLimit) break;

      obstacleEngine.spawnFromSegment(levelEngine.segments[i], starts[i]);
      itemEngine.spawnFromSegment(levelEngine.segments[i], starts[i]);

      _spawnedSegmentCount = i + 1;
    }
  }

  void _resolveCollisions() {
    // Obstacles
    for (final obstacle in obstacleEngine.obstaclesNear(
      distanceMeters,
      forwardSpeed: physics.forwardSpeed,
    )) {
      if (obstacle.isHit || obstacle.isPassed) continue;

      final hit = collisionEngine.checkObstacleHit(
        obstacle: obstacle,
        physics: physics,
        previousRunnerDistance: previousDistanceMeters,
        runnerDistance: distanceMeters,
      );

      if (hit) {
        obstacle.isHit = true;
        _applyHit();
      } else if (obstacle.distance < distanceMeters &&
          obstacle.distance >= previousDistanceMeters) {
        obstacle.isPassed = true;
        scoreEngine.registerObstacleAvoided();
      }
    }

    // Items
    final magnetRadius = itemEngine.hasMagnet ? 6.0 : 0.0;

    for (final item in itemEngine.itemsNear(
      distanceMeters,
      forwardSpeed: physics.forwardSpeed,
    )) {
      final collected = collisionEngine.checkItemCollected(
        item: item,
        physics: physics,
        previousRunnerDistance: previousDistanceMeters,
        runnerDistance: distanceMeters,
        magnetRadius: magnetRadius,
      );

      if (collected) {
        _collectItem(item);
      }
    }

    itemEngine.pruneCollectedAndPassed(distanceMeters);
  }

  void _collectItem(ItemInstance item) {
    itemEngine.collect(item);
    scoreEngine.registerItem(item.type);

    if (item.type == ItemType.energyCan || item.type == ItemType.bonusCan) {
      levelEngine.registerCan();
      AudioManager.instance.playCanCollect();
    } else if (item.type == ItemType.coin) {
      levelEngine.registerCoin();
      AudioManager.instance.playCoinCollect();
    }

    if (isPowerUpItem(item.type)) {
      final powerUpType = _powerUpTypeFor(item.type);
      if (powerUpType != null) {
        itemEngine.activatePowerUp(powerUpType);
        _reflectPowerUpOnRunner();
        _playPowerUpSfx(powerUpType);
      }
    }
  }

  PowerUpType? _powerUpTypeFor(ItemType type) {
    switch (type) {
      case ItemType.magnet:
        return PowerUpType.magnet;
      case ItemType.shield:
        return PowerUpType.shield;
      case ItemType.speedBoost:
        return PowerUpType.speedBoost;
      case ItemType.invincibility:
        return PowerUpType.invincibility;
      default:
        return null;
    }
  }

  void _playPowerUpSfx(PowerUpType type) {
    switch (type) {
      case PowerUpType.magnet:
        AudioManager.instance.playMagnetActivate();
        break;
      case PowerUpType.shield:
        break;
      case PowerUpType.speedBoost:
        AudioManager.instance.playSpeedBoost();
        break;
      case PowerUpType.invincibility:
        AudioManager.instance.playInvincibility();
        break;
    }
  }

  void _reflectPowerUpOnRunner() {
    runner.hasShield = itemEngine.hasShield;
    runner.isMagnetActive = itemEngine.hasMagnet;
    runner.isSpeedBoostActive = itemEngine.hasSpeedBoost;
    runner.isInvincible = itemEngine.hasInvincibility;
  }

  void _applyHit() {
    if (_hitInvulnerabilitySeconds > 0) return;

    final shieldAbsorbed = itemEngine.consumeShieldHit();
    if (shieldAbsorbed) {
      runner.hasShield = false;
      AudioManager.instance.playShieldBreak();
      return;
    }

    final lostLife = collisionEngine.applyHit(runner);
    levelEngine.registerHit();

    if (lostLife) {
      AudioManager.instance.playPlayerHit();

      cameraEngine.shake(
        durationSeconds: GameConstants.cameraShakeDurationSeconds,
        magnitude: GameConstants.cameraShakeMagnitude,
      );

      _hitInvulnerabilitySeconds = 1.0;

      if (runner.lives <= 0) {
        endReason = RunEndReason.gameOver;
      } else {
        _respawnAtCheckpoint();
      }
    }
  }

  void _respawnAtCheckpoint() {
    final checkpoint = levelEngine.lastReachedCheckpoint;
    if (checkpoint != null) {
      distanceMeters = checkpoint.distance;
      // Prevent the next frame from treating the respawn itself as a
      // giant distance crossing.
      previousDistanceMeters = distanceMeters;
      AudioManager.instance.playCheckpoint();
    }
  }

  void _checkEndConditions() {
    if (endReason != RunEndReason.none) return;

    if (levelEngine.progress.isComplete) {
      scoreEngine.registerLevelCompletion();
      endReason = RunEndReason.levelComplete;
      runner.state = RunnerState.celebrating;
      AudioManager.instance.playLevelComplete();
    } else if (runner.lives <= 0) {
      endReason = RunEndReason.gameOver;
      AudioManager.instance.playGameOver();
    }
  }

  void reset() {
    distanceMeters = 0;
    previousDistanceMeters = 0;

    _spawnedSegmentCount = 0;

    endReason = RunEndReason.none;

    _hitInvulnerabilitySeconds = 0;

    scoreEngine.reset();
    obstacleEngine.reset();
    itemEngine.reset();
    cameraEngine.reset();

    runner.lives = GameConstants.startingLives;
    runner.state = RunnerState.running;

    _spawnUpcomingSegments();
  }
}
